#'''Parameters config.'''#


# --- general --- #

ext: ''
mask: False 
metaphlan: True 
kraken2: True 
# xtree kingdom options: bacterial_archaeal, viral, protozoa_fungi
# Separate options on one line with commas (ex. viral,protozoa_fungi)
xtree: 'bacterial_archaeal,protozoa_fungi,viral'
min_rel_abund: 0


# --- metaphlan --- #

metaphlan_database: ''


# --- kraken2/bracken --- #

kraken_bracken_database: ''
kraken2_executable: ''
read_len: 100


# --- xtree --- #

bacterial_archaeal_database: ''
viral_database: ''
protozoa_fungi_database: ''
xtree_executable: ''
ncbi_tax_names: ''
# Original defaults: 0.02 (thresh = min_rel_abund), 0.05, 0.01
hthresh : 0
uthresh : 0
