#'''Parameters config.'''

# --- general --- #

ext: ''
conda_prefix: ''
metaphlan: True
kraken2: True
min_rel_abund: 0.001


# --- masking --- #

mask: False
bbmask_script: ''


# --- metaphlan --- #

metaphlan_database: ''


# --- kraken2/bracken --- #

kraken_bracken_database: ''
read_len: 150
