#'''Parameters config.'''#

# --- general --- #

taxthreads: 8
mask: True 
mode: 'all' # options: kraken2 (default), MetaPhlAn3, all

# --- MetaPhlAn3_params --- #
MetaPhlAn3_database_location: "/athena/masonlab/scratch/users/btt4001/databases/humann3_databases/metaphlan3"

# --- kraken/bracken_params --- #
kraken_bracken_database_location: "/home/cem2009/ReferenceFiles/kraken2/databases/humanmicroorg"
bracken_readlength: 150
