#'''Parameters config.'''#


# --- general --- #

ext: ''
mask: False 
metaphlan: False 
kraken2: True 
# xtree kingdom options: bacterial_archaeal, viral, protozoa_fungi
# Separate options on one line with commas (ex. viral,protozoa_fungi)
xtree: 'bacterial_archaeal,protozoa_fungi,viral'


# --- metaphlan --- #

metaphlan_database: ''


# --- kraken2/bracken --- #

kraken_bracken_database: ''
kraken2_executable: ''
read_len: 150


# --- xtree --- #

bacterial_archaeal_database: ''
viral_database: ''
protozoa_fungi_database: ''
xtree_executable: ''
ncbi_tax_names: ''
thresh: 0.02
hthresh : 0.05
uthresh : 0.01
