#'''Parameters config.'''#


# --- general --- #

ext: "~/bin/camp_short-read-taxonomy/workflow/ext"
mask: False 
metaphlan: False 
kraken2: True 
# xtree kingdom options: bacterial_archaeal, viral, protozoa_fungi
# Separate options on one line with commas (ex. viral,protozoa_fungi)
xtree: 


# --- metaphlan --- #

metaphlan_database: "~/bin/databases/metaphlan_20220926"


# --- kraken2/bracken --- #

kraken_bracken_database: "~/bin/databases/Kraken2"
kraken2_executable: "~/bin/kraken2"
read_len: 150


# --- xtree --- #

bacterial_archaeal_database: "~/bin/databases/GTDB207_filt.xtr"
viral_database: "~/bin/databases/genbankviralcomplete_99percclust_k17_comp0_20220726.xtr"
protozoa_fungi_database: "~/bin/databases/genbank_fungi_protozoa_complete_20220726.xtr"
xtree_executable: "~/bin/xtree_recompile"
thresh: 0.02
hthresh : 0.05
uthresh : 0.01
