#'''Parameters config.'''#

# --- general --- #

taxthreads: 8
mask: False 
MetaPhlAn3: False 
kraken2: False 
xtree_bacterial_archaeal: False 
xtree_viral: True 
xtree_fungi_protozoa: False 

# --- MetaPhlAn3_params --- #
MetaPhlAn3_database_location: "/athena/masonlab/scratch/users/btt4001/databases/humann3_databases/metaphlan3"

# --- kraken/bracken_params --- #
kraken_bracken_database_location: "/home/cem2009/ReferenceFiles/kraken2/databases/humanmicroorg"
bracken_readlength: 150

# --- xtree_params --- #
xtree_gtdb_database_location: "/athena/masonlab/scratch/users/btt4001/databases/xtree_db/xtree_db_gtdb207_kmer29_comp2_20220722/GTDB207_filt.xtr"
xtree_viral_database_location: "/athena/masonlab/scratch/users/btt4001/databases/xtree_db/xtree_db_genbankviralcomplete_99percclust_k17_comp0_20220726/genbankviralcomplete_99percclust_k17_comp0_20220726.xtr"
xtree_fungiprotozoa_database_location: "/athena/masonlab/scratch/users/btt4001/databases/xtree_db/xtree_db_genbank_fungi_protozoa_complete_20220726/genbank_fungi_protozoa_complete_20220726.xtr"
xtree_executable: "~/UTree/xtree_recompile"
mappingfile_loc: "/athena/masonlab/scratch/users/btt4001/camp_dev/camp_short-read-taxonomy/ext_files/xtree_all_db_mapping"
thresh_bac: 0.02
hthresh_bac : 0.05
uthresh_bac : 0.01
thresh_viral: 0.02
hthresh_viral : 0.05
uthresh_viral : 0.01
thresh_fungprot: 0.02
hthresh_fungprot : 0.05
uthresh_fungprot : 0.01