#'''Command-line usage resource config.'''#


# --- mask_reads --- #

mask_reads_threads: 30


# --- scrub_fastq_captions --- #

scrub_fastq_mem_mb: 150000


# --- metaphlan --- #

metaphlan_threads: 30
metaphlan_mem_mb: 100000


# --- kraken2 --- #

kraken2_threads: 30
kraken2_mem_mb: 150000


# --- xtree --- #

xtree_threads: 30
xtree_mem_mb: 200000
