#'''Command-line usage resource config.'''#


# --- mask_reads --- #

mask_reads_threads: 10


# --- scrub_fastq_captions --- #

scrub_fastq_mem_mb: 150000

# --- metaphlan --- #

metaphlan_threads: 20
metaphlan_mem_mb: 50000


# --- kraken2 --- #

kraken2_threads: 20
kraken2_mem_mb: 50000


# --- xtree --- #

xtree_threads: 10
xtree_mem_mb: 30000
